### ISSUE TITLE
Problem when insert-sample <login> <pwd>.

### ISSUE THREAD

**Issue by nikilmethew** [docdoku/docdoku-plm-docker#11]
HI,

To import and check sample project I have used the following command. 

> sudo ./platform-ctl insert-sample MY_LOGIN_USER_ID MY_PASSWORD

When trying the above command it gives me the following error.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.571 s
[INFO] Finished at: 2019-01-31T07:29:36+00:00
[INFO] Final Memory: 34M/301M
[INFO] ------------------------------------------------------------------------
[INFO] - No workspace name supplied, generating one...
[INFO] - Using wks-a72fca63 as workspace name 
[INFO] - Starting load process... 
[INFO] - Checking server availability...
[INFO] - Creating your account...
[INFO] - Creating account [sommesh29]
[INFO] - Cannot create account, trying to use given credentials for next operations
[INFO] - Creating workspace...
[INFO] - Adding user sommesh29 to workspace wks-a72fca63
[SEVERE] - Ooops, something went wrong while loading sample data : Not Found
Not Foundcom.docdoku.api.client.ApiException: Not Found
    at com.docdoku.api.client.ApiClient.handleResponse(ApiClient.java:838)
    at com.docdoku.api.client.ApiClient.execute(ApiClient.java:773)
    at com.docdoku.api.client.ApiClient.execute(ApiClient.java:757)
    at com.docdoku.api.services.WorkspacesApi.addUserWithHttpInfo(WorkspacesApi.java:833)
    at com.docdoku.api.services.WorkspacesApi.addUser(WorkspacesApi.java:819)
    at com.docdoku.loaders.SampleLoader.addUserToWorkspace(SampleLoader.java:304)
    at com.docdoku.loaders.SampleLoader.load(SampleLoader.java:88)
    at com.docdoku.loaders.Main.main(Main.java:73)

```

Kindly let me know the reson for the error .

Is this error from your API repositroy or so?

**Comment by nikilmethew** [comment]
Pulled the latest changes.

When calling the below command



> sudo ./platform-ctl health

Getting the below error.

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara Server  4.1.2.181 #badassfish - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Internal Server Error</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Internal Server Error</p><p><b>description</b>The server encountered an internal error that prevented it from fulfilling this request.</p><hr/><h3>Payara Server  4.1.2.181 #badassfish</h3></body></html>`

But the Local site is running.
